spring.application.name=beatmanager

spring.datasource.url=jdbc:postgresql://localhost:5432/beatmanager
spring.datasource.username=postgres
spring.datasource.password=1708
spring.flyway.enabled=true
spring.jpa.hibernate.ddl-auto=validate

server.port=8081