spring.application.name=beatmanager

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.flyway.enabled=true
spring.jpa.hibernate.ddl-auto=validate

server.port=${SERVER_PORT}

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}
