# Desenvolvimento - configuracoes locais

spring.datasource.url=jdbc:postgresql://localhost:5432/beatmanager
spring.datasource.username=postgres
spring.datasource.password=1708

server.port=8081

jwt.secret=YmVhdG1hbmFnZXItc2VjcmV0LWtleS1mb3Itand0LXRva2VuLWdlbmVyYXRpb24tMjAyNg==

# CORS
cors.allowed-origins=http://localhost:3000

# Upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Cloudinary
cloudinary.cloud-name=fgcijq7r
cloudinary.api-key=922832792649577
cloudinary.api-secret=RT3Y9E9d5FxfNMRdgfmIQQNzP6k
