# Desenvolvimento - configurações locais

spring.datasource.url=jdbc:postgresql://localhost:5432/beatmanager
spring.datasource.username=postgres
spring.datasource.password=1708

server.port=8081

jwt.secret=YmVhdG1hbmFnZXItc2VjcmV0LWtleS1mb3Itand0LXRva2VuLWdlbmVyYXRpb24tMjAyNg==
